route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: "amitvashist7@gmail.com"
    from: "amitvashist7@gmail.com"
    smarthost: smtp.gmail.com:587
    auth_username: "amitvashist7@gmail.com"
    auth_identity: "amitvashist7@gmail.com"
    auth_password: "<<token>>"
    send_resolved: true
