global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@terraform.example.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  repeat_interval: 1h
  receiver: operations-team

receivers:
- name: 'operations-team'
  email_configs:
  - to: 'amitvashist7@gmail.com'
    from: $GMAIL_ACCOUNT
    smarthost: smtp.gmail.com:587
    auth_username: "$GMAIL_ACCOUNT"
    auth_identity: "$GMAIL_ACCOUNT"
    auth_password: "$GMAIL_AUTH_TOKEN"
  #slack_configs:
  #- api_url: https://hooks.slack.com/services/XXXXXX/XXXXXX/XXXXXX
  #  channel: '#prometheus-course'
    send_resolved: true

